import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import { ServerComponent } from './server/server.component';
import { ServersComponent } from './servers/servers.component';


@NgModule({
  declarations: [
    AppComponent,
    //we add ServerComponenent after we have created server.component.html and server.component.ts after that we add the import
    ServerComponent,
    ServersComponent //this was generated by the ng generate component servers in short ng g c servers
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,

  ],
  providers: [],
  //tells the component for what component it should recommend it.
  bootstrap: [AppComponent]
})
export class AppModule { }
